// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwYjNi4_sch2Gu_liZBTon67RpzGSCJT8',
    appId: '1:18165870274:web:35ac1a232c7f11b127d55b',
    messagingSenderId: '18165870274',
    projectId: 'bibliotecaapp-a2d41',
    authDomain: 'bibliotecaapp-a2d41.firebaseapp.com',
    storageBucket: 'bibliotecaapp-a2d41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfuPi3o1nfA5PCneR4UZUyy5q8Z-tTSpM',
    appId: '1:18165870274:android:d6264f6b4bb9391a27d55b',
    messagingSenderId: '18165870274',
    projectId: 'bibliotecaapp-a2d41',
    storageBucket: 'bibliotecaapp-a2d41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-aeAHPN7dDrSN7LFwsiUisYKXKhpVdLo',
    appId: '1:18165870274:ios:c7d5185f3ec4c53d27d55b',
    messagingSenderId: '18165870274',
    projectId: 'bibliotecaapp-a2d41',
    storageBucket: 'bibliotecaapp-a2d41.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-aeAHPN7dDrSN7LFwsiUisYKXKhpVdLo',
    appId: '1:18165870274:ios:c7d5185f3ec4c53d27d55b',
    messagingSenderId: '18165870274',
    projectId: 'bibliotecaapp-a2d41',
    storageBucket: 'bibliotecaapp-a2d41.firebasestorage.app',
    iosBundleId: 'com.example.bibliotecaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwYjNi4_sch2Gu_liZBTon67RpzGSCJT8',
    appId: '1:18165870274:web:1033dd4254a6392e27d55b',
    messagingSenderId: '18165870274',
    projectId: 'bibliotecaapp-a2d41',
    authDomain: 'bibliotecaapp-a2d41.firebaseapp.com',
    storageBucket: 'bibliotecaapp-a2d41.firebasestorage.app',
  );
}
